linters:
- header:
- import:
    packages: ['cellcutoff']
- namespace:
    filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '+ *.py']
- pylint:
- pycodestyle:
    config: .pycodestylerc
- pydocstyle:
- whitespace:
