#!/usr/bin/env python
# -*- coding: utf-8 -*-
# QCGrids is a numerical integration library for quantum chemistry.
# Copyright (C) 2011-2017 The QCGrids developers
#
# This file is part of QCGrids.
#
# QCGrids is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# QCGrids is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>
# --

from __future__ import print_function

import argparse
import sys
import urllib.request

import os
from stat import S_IREAD, S_IRGRP, S_IROTH, S_IWUSR


def set_ro(fn):
    os.chmod(fn, S_IREAD | S_IRGRP | S_IROTH)


def unset_ro(fn):
    os.chmod(fn, S_IWUSR | S_IREAD)


def main():
    parser = argparse.ArgumentParser(description="Apply templates to a Travis file.")
    parser.add_argument("file", help="The travis file to apply the template on.")
    parser.add_argument("--template", "-t",
                        help="An alternate source for the template. Ignores the URL.")
    args = parser.parse_args()

    unique = []
    url = None
    with open(args.file) as fh:
        for line in fh:
            if line.startswith('# EVERYTHING BELOW THIS LINE IS AUTOGENERATED.') or \
                    line.startswith('# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs'):
                unique.append(line)
                break
            elif line.startswith('# TEMPLATED FROM '):
                url = line.split()[-1]
            unique.append(line)

    if args.template:
        with open(args.template) as fh:
            template = fh.read()
    elif url:
        with urllib.request.urlopen(url) as response:
            template = response.read().decode()
    else:
        raise ValueError

    template = template.split("\n")
    for i, l in enumerate(template):
        if l.startswith('# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs'):
            template = template[i + 1:]
            break
    template = "\n".join(template)

    unset_ro(args.file)
    with open(args.file, "w") as fh:
        fh.write("".join(unique))
        fh.write(template)
    set_ro(args.file)


if __name__ == '__main__':
    main()
